### ISSUE TITLE
How to add AED packages

### ISSUE THREAD

**Issue by Hanqingpeng** [romunov/AED#2]
I don't know how to add AED packages
install.packages("AED")
or devtools::install_github("romunov/AED
+ ")

Its no OK

**Comment by romunov** [comment]
You are probably missing the full toolchain (Rtools). Works for me, though.

```r
> library(devtools)
Error in library(devtools) : there is no package called ‘devtools’
> install.packages("devtools")
Installing package into ‘C:/Users/romunov/Documents/R/win-library/3.4’
(as ‘lib’ is unspecified)
also installing the dependencies ‘memoise’, ‘git2r’

trying URL 'https://cran.wu.ac.at/bin/windows/contrib/3.4/memoise_1.1.0.zip'
Content type 'application/zip' length 29903 bytes (29 KB)
downloaded 29 KB

trying URL 'https://cran.wu.ac.at/bin/windows/contrib/3.4/git2r_0.21.0.zip'
Content type 'application/zip' length 3030000 bytes (2.9 MB)
downloaded 2.9 MB

trying URL 'https://cran.wu.ac.at/bin/windows/contrib/3.4/devtools_1.13.4.zip'
Content type 'application/zip' length 443915 bytes (433 KB)
downloaded 433 KB

package ‘memoise’ successfully unpacked and MD5 sums checked
package ‘git2r’ successfully unpacked and MD5 sums checked
package ‘devtools’ successfully unpacked and MD5 sums checked

The downloaded binary packages are in
	C:\Users\romunov\AppData\Local\Temp\RtmpugjwkQ\downloaded_packages
> devtools::install_github("romunov/AED")
Downloading GitHub repo romunov/AED@master
from URL https://api.github.com/repos/romunov/AED/zipball/master
Installing AED
"C:/PROGRA~1/R/R-34~1.2/bin/x64/R" --no-site-file --no-environ --no-save  \
  --no-restore --quiet CMD INSTALL  \
  "C:/Users/romunov/AppData/Local/Temp/RtmpugjwkQ/devtools2fdc7ae178bd/romunov-AED-19e2ec6"  \
  --library="C:/Users/romunov/Documents/R/win-library/3.4" --install-tests 

* installing *source* package 'AED' ...
** R
** data
** preparing package for lazy loading
** help
*** installing help indices
** building package indices
** testing if installed package can be loaded
*** arch - i386
*** arch - x64
* DONE (AED)
```

**Comment by Hanqingpeng** [comment]
Thank you for your help. Its ok.

**Comment by KyleOng** [comment]
I'm having this error while following your installation procedure. Btw, Im using 
Ubuntu 20.04.1 LTS.
```
> devtools::install_github("romunov/AED")
Downloading GitHub repo romunov/AED@HEAD
sh: 1: /bin/gtar: not found
sh: 1: /bin/gtar: not found
Error: Failed to install 'AED' from GitHub:
  error in running command
In addition: Warning messages:
1: In system(cmd) : error in running command
2: In utils::untar(tarfile, ...) :
  ‘/bin/gtar -xf '/tmp/RtmpaeC7Dz/file1832278530ec.tar.gz' -C '/tmp/RtmpaeC7Dz/remotes18326c45de80'’ returned   error code 127
```


> You are probably missing the full toolchain (Rtools). Works for me, though.
> 
> ```r
> > library(devtools)
> Error in library(devtools) : there is no package called ‘devtools’
> > install.packages("devtools")
> Installing package into ‘C:/Users/romunov/Documents/R/win-library/3.4’
> (as ‘lib’ is unspecified)
> also installing the dependencies ‘memoise’, ‘git2r’
> 
> trying URL 'https://cran.wu.ac.at/bin/windows/contrib/3.4/memoise_1.1.0.zip'
> Content type 'application/zip' length 29903 bytes (29 KB)
> downloaded 29 KB
> 
> trying URL 'https://cran.wu.ac.at/bin/windows/contrib/3.4/git2r_0.21.0.zip'
> Content type 'application/zip' length 3030000 bytes (2.9 MB)
> downloaded 2.9 MB
> 
> trying URL 'https://cran.wu.ac.at/bin/windows/contrib/3.4/devtools_1.13.4.zip'
> Content type 'application/zip' length 443915 bytes (433 KB)
> downloaded 433 KB
> 
> package ‘memoise’ successfully unpacked and MD5 sums checked
> package ‘git2r’ successfully unpacked and MD5 sums checked
> package ‘devtools’ successfully unpacked and MD5 sums checked
> 
> The downloaded binary packages are in
> 	C:\Users\romunov\AppData\Local\Temp\RtmpugjwkQ\downloaded_packages
> > devtools::install_github("romunov/AED")
> Downloading GitHub repo romunov/AED@master
> from URL https://api.github.com/repos/romunov/AED/zipball/master
> Installing AED
> "C:/PROGRA~1/R/R-34~1.2/bin/x64/R" --no-site-file --no-environ --no-save  \
>   --no-restore --quiet CMD INSTALL  \
>   "C:/Users/romunov/AppData/Local/Temp/RtmpugjwkQ/devtools2fdc7ae178bd/romunov-AED-19e2ec6"  \
>   --library="C:/Users/romunov/Documents/R/win-library/3.4" --install-tests 
> 
> * installing *source* package 'AED' ...
> ** R
> ** data
> ** preparing package for lazy loading
> ** help
> *** installing help indices
> ** building package indices
> ** testing if installed package can be loaded
> *** arch - i386
> *** arch - x64
> * DONE (AED)
> ```
